[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-lite-admin"
version = "0.1.8"
description = "A lightweight, pluggable admin panel for FastAPI"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
    "fastapi>=0.100.0",
    "sqlalchemy>=2.0.0",
    "pydantic>=2.0.0",
    "jinja2>=3.1.0",
    "python-multipart>=0.0.6"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
    "uvicorn"
]

[tool.setuptools.packages.find]
include = ["fastapi_admin_lite*"]
exclude = ["example*"]

[tool.setuptools.package-data]
"fastapi_admin_lite.ui.templates" = ["*.html"]

[project.urls]
Homepage = "https://github.com/rishiqwerty/admin-panel-fast-api"
Repository = "https://github.com/rishiqwerty/admin-panel-fast-api"
